# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Configuration for the first .NET project
  - package-ecosystem: "nuget"
    directory: "/" # Path to the first project
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "[dependency update]" # Prefix for the commit message and PR title
    pull-request-branch-name:
      separator: "-" # Customize the branch name for PRs
    # Automatically set assignees for the pull requests
    assignees:
      - "chismaeel"
    # Add labels to the pull request if needed
    labels:
      - "dependencies"
    # Additional settings like assignees, labels, etc.

  # Repeat for more .NET projects as needed

  # Configuration for GitHub Actions (optional)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[dependency update]" # Prefix for the commit message and PR title
    pull-request-branch-name:
      separator: "-" # Customize the branch name for PRs
    # Automatically set assignees for the pull requests
    assignees:
      - "chIsmaeel"
    # Add labels to the pull request if needed
    labels:
      - "dependencies"
